Title =  "Geekard"
LanguageCode = "zh-CN"
BaseUrl = "http://blog.opsnull.com"
Theme =  "next"
MetaDataFormat =  "yaml"
CanonifyUrls =  true
BuildDrafts =  false
PaginatePath =  "p"
Paginate = 8
DisablePathToLower =  true
HasCJKLanguage = true
PreserveTaxonomyNames = false
UglyUrls = false
PygmentsStyle = "monokai"
PygmentsUseClasses = true
DefaultContentLanguage = "zh"

[Params]
  Introduce = "Devops & Geeker & Hacker"
  Description = "运维开发 | 博客"
  Keywords =  "Geekard,运维开发,监控,Zabbix,Golang,个人,思考,读书,笔记,技术,分享,极客"
  Subtitle = "一指流沙，IT年华"
  Imglogo = "/img/logo.svg"
  AuthorImg = "/img/author.png"
  DateFormat = "2006-01-02"
  YearFormat = "2006年"
  MonthFormat = "01-02"
  BaiduStatsId = "3a6c58f0013d3cc4ec3e56984c135511"
  QQStatsId = "574419270"
  Fancybox = true

[Author]
  Name = "Geekard"

[Params.Share]
  Baidu = true

[[Menu.Main]]
  Name = "首页"
  Pre = "home"
  URL = "/"
  Weight = 1
[[Menu.Main]]
  Name = "技术"
  Pre = "code"
  URL = "/categories/技术/"
  Weight = 2
[[Menu.Main]]
  Name = "感想"
  Pre = "tint"
  URL = "/categories/感想/"
  Weight = 3
[[Menu.Main]]
  Name = "笔记"
  Pre = "book"
  URL = "/categories/笔记/"
  Weight = 4
[[Menu.Main]]
  Name = "杂记"
  Pre = "leaf"
  URL = "/categories/杂记/"
  Weight = 5
[[Menu.Main]]
  Name = "归档"
  Pre = "archive"
  URL = "/post/"
  Weight = 6
[[Menu.Main]]
  Name = "关于"
  Pre = "user"
  URL = "/about/"
  Weight = 7

[[Params.Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/geekard/"

[[Params.Socials]]
  Name = "知乎"
  Icon = "globe"
  URL = "https://www.zhihu.com/people/geekard" 