BaseURL = "http://opsnull.com/"
LanguageCode = "zh-CN"
HasCJKLanguage = true
Title = "OPSNULL"
Theme = "hugo-pacman-theme"
pygmentsStyle = "default"
pygmentsUseClasses = true
RSSUri = "feed.xml"

[Author]
  Name = "opsnull"

[Params]
  AuthorHomepage = "http://opsnull.com"
  BottomIntroduce = "热爱生活<br/>热爱技术"
  Description = ""
  Subtitle = "No Oops"
  Weibo = "geekard"
  Twitter = "geekard"
  GitHub = "opsnull"
  Imglogo = "img/logo.svg"
  AuthorImg = "img/author.png"
  DateFormat = "2006年01月02日"
  MonthFormat = "2006年01月"
  FancyBox = true

  #[Params.DuoShuo]
  #  ShortName = "coderzh"

  [Params.Disqus]
    ShortName = "coderzh"

  [Params.GoogleAnalytics]
    ID = "UA-10147768-2"

  [Params.Strings]
    Search = "搜索"
    PageNotFound = "你访问的页面不存在"
    ShowSideBar = "显示侧边栏"
    HideSideBar = "隐藏侧边栏"
    Categories = "分类"
    Archive = "归档"
    Tags = "标签"
    TagCloud = "标签云"
    Rss = "RSS 订阅"
    TableOfContents = "文章目录"

[Menu]
  [[Menu.Main]]
    Name = "首页"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "关于"
    URL = "/about"
    Weight = 2
